### ISSUE TITLE
get_s3_credentials will expire after 1-hour

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/EarthData.jl#1]
I believe the temporary credentials issued by nasa expire after 1-hour. I wonder if we should include some auto-renew functionality. 

I would also be tempted to keep variable names unchanged, e.g.

`expiry = DateTime(body.expiration, dateformat"y-m-d H:M:S+z")`

I would change to

 `expiration = DateTime(body.expiration, dateformat"y-m-d H:M:S+z")`
 
 This will make it easier for other to intuit variable names if they come with experience from another language / package

**Comment by evetion** [comment]
Ah, yes I just have to port the functionality from SpaceLiDAR, we do the renewal in the download function over there.

I was planning on making this aws part a package extension on AWSS3.

**Comment by evetion** [comment]
Should now be fixed on master. I'm planning on registering the package as is.
